AWSTemplateFormatVersion: 2010-09-09
Description: creates a serverless api that returns pre-signed urls
Transform: AWS::Serverless-2016-10-31

Resources:
  rAuthApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowHeaders:
          - "*"   
        AllowMethods:
          - GET
          - POST
          - OPTIONS
        AllowOrigins: 
          - "d1p4etgsrvfxla.cloudfront.net"

  rAuthFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: code/
      Environment:
        Variables:
          UploadBucket: !Ref rPictureBucket  
      Events:
        UploadAssetAPI:
          Type: HttpApi
          Properties:
            ApiId: !Ref rAuthApi
            Method: GET
            Path: /auth
      FunctionName: cgc0121-auth
      Handler: auth.handler
      MemorySize: 128
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref rPictureBucket
        - S3WritePolicy:
            BucketName: !Ref rPictureBucket
      Runtime: nodejs12.x
      Timeout: 5
            
  rPictureBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: wheeler-cgc0121-pictures
      CorsConfiguration:
        CorsRules:
        - AllowedHeaders:
            - "*"
          AllowedMethods:
            - GET
            - PUT
          AllowedOrigins:
            - "d1p4etgsrvfxla.cloudfront.net"

Outputs:
  oAuthApiEndpoint:
    Description: Auth API Endpoint
    Value: !Sub "https://${rAuthApi}.execute-api.${AWS::Region}.amazonaws.com"
  oPictureBucket:
    Description: S3 Bucket for Storing Pictures
    Value: !Ref rPictureBucket

