AWSTemplateFormatVersion: 2010-09-09
Description: creates a serverless api that returns pre-signed urls
Transform: AWS::Serverless-2016-10-31

Resources:
  rApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowHeaders:
          - "*"   
        AllowMethods:
          - GET
          - POST
          - OPTIONS
        AllowOrigins: 
          - "https://d1p4etgsrvfxla.cloudfront.net"

  rAmazonAuthFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: aws-code/
      Environment:
        Variables:
          rPictureBucket: !Ref rPictureBucket  
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref rApi
            Method: GET
            Path: /getAmazonPresignedUrl
      FunctionName: cgc0121-getAmazonPresignedUrl
      Handler: index.handler
      MemorySize: 128
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref rPictureBucket
        - S3WritePolicy:
            BucketName: !Ref rPictureBucket
      Runtime: nodejs12.x
      Timeout: 5

  rAzureTableFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: azure-code/
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref rApi
            Method: GET
            Path: /queryAzureAnalysisTable
      FunctionName: cgc0121-queryAzureAnalysisTable
      Handler: index.handler
      MemorySize: 128
      Runtime: nodejs12.x
      Timeout: 5
            
  rPictureBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: wheeler-cgc0121-pictures
      CorsConfiguration:
        CorsRules:
        - AllowedHeaders:
            - "*"
          AllowedMethods:
            - GET
            - PUT
          AllowedOrigins:
            - "*"

Outputs:
  oApiEndpoint:
    Description: Auth API Endpoint
    Value: !Sub "https://${rApi}.execute-api.${AWS::Region}.amazonaws.com"
  oPictureBucket:
    Description: S3 Bucket for Storing Pictures
    Value: !Ref rPictureBucket

